# Generated by Django 3.2 on 2021-05-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210507_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='title',
            field=models.CharField(default=0, max_length=500000),
            preserve_default=False,
        ),
    ]
