# Generated by Django 3.2 on 2021-05-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_artical_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='articals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500000)),
                ('title', models.CharField(max_length=500000)),
                ('email', models.CharField(max_length=500000)),
                ('art', models.TextField()),
            ],
        ),
    ]
